/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
       colors: {
                "secondary-fixed-dim": "#c8c6c5",
                "on-primary-fixed-variant": "#7c2e19",
                "on-tertiary-fixed-variant": "#005144",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "surface": "#fafaf5",
                "tertiary": "#006b5b",
                "on-secondary-fixed": "#1b1c1c",
                "tertiary-container": "#19a992",
                "outline": "#88726d",
                "secondary": "#5f5e5e",
                "inverse-surface": "#2f312e",
                "on-primary-container": "#5b1604",
                "primary": "#9a442d",
                "on-secondary-fixed-variant": "#474747",
                "surface-dim": "#dadad5",
                "on-primary": "#ffffff",
                "outline-variant": "#dbc1ba",
                "surface-container": "#eeeee9",
                "secondary-container": "#e4e2e1",
                "surface-variant": "#e3e3de",
                "surface-tint": "#9a442d",
                "on-secondary-container": "#656464",
                "surface-container-lowest": "#ffffff",
                "on-background": "#1a1c19",
                "inverse-primary": "#ffb4a1",
                "on-surface": "#1a1c19",
                "surface-container-high": "#e8e8e3",
                "inverse-on-surface": "#f1f1ec",
                "primary-container": "#e07a5f",
                "primary-fixed": "#ffdbd2",
                "error-container": "#ffdad6",
                "on-tertiary-container": "#00362d",
                "error": "#ba1a1a",
                "secondary-fixed": "#e4e2e1",
                "surface-container-highest": "#e3e3de",
                "on-primary-fixed": "#3c0800",
                "background": "#fafaf5",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "surface-container-low": "#f4f4ef",
                "surface-bright": "#fafaf5",
                "primary-fixed-dim": "#ffb4a1",
                "on-tertiary-fixed": "#00201a",
                "tertiary-fixed": "#7df7dd",
                "on-surface-variant": "#55423e",
                "tertiary-fixed-dim": "#5edbc1"
              },
               fontFamily: {
                "headline": ["Manrope"],
                "body": ["Manrope"],
                "label": ["Inter"]
              },
              borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}

